import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import { AuthContext } from '../context/auth'
import { useContext } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const {user} = useContext(AuthContext)

  const Redirect=()=>{
    const router =useRouter();
    router.push('./login')
    return null;
  }
  return (
    <div>
      <Head>
        <title>reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Protected Route (if user exits show the feed else redirect to login) */}
    {
    // The ?. operator is like the . chaining operator, except that instead of causing an error if a reference is nullish (null or undefined), the expression short-circuits with a return value of undefined.
     user?.uid ? <Feed/> :<Redirect></Redirect>
    }
      <Feed></Feed>
    </div>
  )
}
